### ISSUE TITLE
Unable to Create Database in PHP 7

### ISSUE THREAD

**Issue by varshanbp** [varshanbp/Login-System-for-Digital-Attendance#3]
Unable to Create Database in PHP7

**Comment by suvithk1** [comment]
duplicate issue

**Comment by drjohnsons** [comment]
Problem creating database

**Comment by drjohnsons** [comment]
Find alternative solution

**Comment by varshanbp** [comment]
Solution found. Updating Soon. Once Solved will be commited to repository.

**Comment by varshanbp** [comment]
Problem Solved. As of new commit on Jan 4, 2016.
Please visit new Commit 7597f60

**Comment by varshanbp** [comment]
As Problem is solved I am closing the Issue.
