### ISSUE TITLE
Forgot Password Button Not Working

### ISSUE THREAD

**Issue by drjohnsons** [varshanbp/Login-System-for-Digital-Attendance#7]
"Forgot Password" Button Not Working and No where Code is designed/coded/specified in for "Forgot Password".

**Comment by varshanbp** [comment]
Noted Down. Will be updated soon/committed soon.

**Comment by varshanbp** [comment]
Problem Solved. Check Latest Version

**Comment by varshanbp** [comment]
This Issue development is stalled as of now. Please recreate in https://github.com/varshanbp/Digital-Attendance
